apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world-vue-app
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: hello-world
        framework: vueapp.js
    spec:     # pod spec                  
      containers:
      - name: hello-world
        image: 319634644076.dkr.ecr.us-east-1.amazonaws.com/vueapp:latest # image we pushed
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-vue-app-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31821
  selector:
    app: hello-world
